### ISSUE TITLE
[Question] On updating to Microsoft.Bot.Connector v3.11.0.0 triggers error: "Strong Name Validation failed"

### ISSUE THREAD

**Issue by SyrianBallaS** [Microsoft/BotBuilder#3666]
## Bot Info 
* SDK Platform: .NET
* SDK Version: 3.9.1 (the issue is with 3.11.0 on NuGet)

## Issue Description
Very similar to closed [issue 3103](https://github.com/Microsoft/BotBuilder/issues/3103).
Except it has to do with the Microsoft.Bot.Connector.dll.

## Code Example
No code, an exception just gets thrown that the assembly doesn't have a strong name.
![image](https://user-images.githubusercontent.com/18649925/32016578-4cc6bc64-b992-11e7-91e5-ae9eb8fe8db7.png)

## Reproduction Steps
1.  Update the assembly/package the 3.11.0 version
2.  Build the project

## Expected Behavior
It should just build and run without error.

## Actual Results
1. If you are using the "Bot Application" template, the project won't even build and give the error
2. If you are using the "Bot Application Core" template, the project will build but will throw a System.IO.FileLoadException almost immediately

**Comment by JasonSowers** [comment]
Which version of visual studio are you using?  I just used the bot application template in visual studio 2017 and was unable to reproduce.

**Comment by EricDahlvang** [comment]
Please upgrade Microsoft.Bot.Connector to v3.11.1 https://www.nuget.org/packages/Microsoft.Bot.Connector/

**Comment by JasonSowers** [comment]
@SyrianBallaS did this fix your problem?

**Comment by Rambalac** [comment]
Same issue.
Upgraded `"Microsoft.Bot.Builder.Azure": "3.2.2"` to `"Microsoft.Bot.Builder.Azure": "3.2.4"`
Now running function locally returns
```
[2017-11-02 03:05:09] Exception during runtime resolution of assembly 'Microsoft.Bot.Connector, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35': 'System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Bot.Connector, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)                                                                
[2017-11-02 03:05:09] File name: 'Microsoft.Bot.Connector, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)      
[2017-11-02 03:05:09] The Zone of the assembly that failed was:                                                         
[2017-11-02 03:05:09] MyComputer                                                                                        
[2017-11-02 03:05:09]    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)                 
[2017-11-02 03:05:09]    at System.Reflection.Assembly.LoadFile(String path)                                            
[2017-11-02 03:05:09]    at Microsoft.Azure.WebJobs.Script.Description.FunctionMetadataResolver.ResolveAssembly(String assemblyName)                                                                                                            
[2017-11-02 03:05:09]    at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoadContext.ResolveAssembly(String name)                                                                                                                
[2017-11-02 03:05:09]    at Microsoft.Azure.WebJobs.Script.Description.FunctionAssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs args)                                                                                             
[2017-11-02 03:05:09]                                                                                                   
[2017-11-02 03:05:09] '                                                                                                 
[2017-11-02 03:05:09] Unable to find assembly 'Microsoft.Bot.Connector, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Are you missing a private assembly file?                                                           
[2017-11-02 03:05:09] Package references have been updated.                                                             
[2017-11-02 03:05:09] Restoring packages.                                                                               
[2017-11-02 03:05:09] Starting NuGet restore                                                                            
[2017-11-02 03:05:09] Restoring packages for C:\Users\xxxx\Source\Repos\yyyy\messages\project.json... 
[2017-11-02 03:05:10] Committing restore...                                                                             
[2017-11-02 03:05:10] Writing lock file to disk. Path: C:\Users\xxxx\Source\Repos\yyyy\messages\project.lock.json                                                                                                             
[2017-11-02 03:05:10] C:\Users\xxxx\Source\Repos\yyyy\messages\project.json                           
[2017-11-02 03:05:10] Restore completed in 424ms.                                                                       
[2017-11-02 03:05:10]                                                                                                   
[2017-11-02 03:05:10] NuGet Config files used:                                                                          
[2017-11-02 03:05:10]     C:\Users\xxxx\AppData\Roaming\NuGet\NuGet.Config                                      
[2017-11-02 03:05:10]                                                                                                   
[2017-11-02 03:05:10] Feeds used:                                                                                       
[2017-11-02 03:05:10]     https://api.nuget.org/v3/index.json                                                           
[2017-11-02 03:05:10]                                                                                                   
[2017-11-02 03:05:10]                                                                                                   
[2017-11-02 03:05:10] Packages restored.                                                                                
[2017-11-02 03:05:11] error CS1705: Assembly 'Microsoft.Bot.Builder.Azure' with identity 'Microsoft.Bot.Builder.Azure, Version=3.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.Bot.Connector, Version=3.11.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Bot.Connector' with identity 'Microsoft.Bot.Connector, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'          
[2017-11-02 03:05:11]                                                                                                   
[2017-11-02 03:05:11] Function compilation error                                                                        
[2017-11-02 03:05:11]                                                                                                   
[2017-11-02 03:05:11] error CS1705: Assembly 'Microsoft.Bot.Builder.Azure' with identity 'Microsoft.Bot.Builder.Azure, Version=3.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.Bot.Connector, Version=3.11.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Bot.Connector' with identity 'Microsoft.Bot.Connector, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'          
[2017-11-02 03:05:11]                                                                                                   
[2017-11-02 03:05:11] Generating 2 job function(s)
```
Updated projects.json
```
{
  "frameworks": {
    "net46": {}
  },
  "dependencies": {
    "FluentUriBuilder": "1.3.1",
    "Microsoft.AdaptiveCards": "0.5.1",
    "Microsoft.Bot.Builder.Azure": "3.2.4",
    "System.Collections.Immutable": "1.4.0",
    "TimeZoneMapper": "1.2.18",
    "WindowsAzure.Storage": "8.5.0"
  }
}
```

**Comment by Rambalac** [comment]
It looks like 3.11.1 Nuget package contains 3.11.0 dll at least for net45.

**Comment by prabhakarreddy1234** [comment]
I am also facing the same problem.   @Rambalac   did you find any workaround ?

**Comment by ameetkonnur** [comment]
i am too facing the same issue. any solution or workaround ?

**Comment by tsahi** [comment]
I get this when I upgrade from 3.12.2.4 (the default with the Azure Function project template) to 3.14. VS2017 15.5.7.
